version: '3.7'

services:
  postgresdb:
    image: postgres:14.8-alpine3.18
    container_name: postgresdb
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    expose:
     - ${POSTGRES_PORT}
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${POSTGRES_DATA}
    env_file:
      - .env

  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    expose:
      - ${REDIS_PORT}
    volumes: 
      - ${REDIS_DATA_PATH}:/data
      - ${REDIS_DATA_PATH}:/mounted-etc/redis.conf
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env

  celery-broker:
    container_name: celery-broker
    image: redis:6.2-alpine
    restart: always
    expose:
      - ${CELERY_BROKER_PORT}
    volumes: 
      - ${CELERY_BROKER_DATA_PATH}:/data
      - ${CELERY_BROKER_DATA_PATH}:/mounted-etc/redis.conf
    env_file:
      - .env

  celery:
    container_name: celery
    build: ./auth_service/
    command: bash run_celery_worker.sh
    depends_on:
      - celery-broker
    
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    expose:
      - ${MONGO_PORT}
    volumes:
      - ${MONGO_DATA_PATH}:/data/db
    env_file:
      - .env

  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper-1
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    expose:
      - 2181
    volumes:
      - ${KAFKA_DATA_PATH}/zookeeper-1/data:/var/lib/zookeeper/data
      - ${KAFKA_DATA_PATH}/zookeeper-1/log:/var/lib/zookeeper/log
    env_file:
      - .env

  zookeeper-2:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper-2
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    expose:
      - 2181
    volumes:
      - ${KAFKA_DATA_PATH}/zookeeper-2/data:/var/lib/zookeeper/data
      - ${KAFKA_DATA_PATH}/zookeeper-2/log:/var/lib/zookeeper/log
    env_file:
      - .env

  kafka-1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-1
    expose:
      - 19091
    depends_on:
      - zookeeper-1
      - zookeeper-2
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-1:2181,zookeeper-2:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:19091,PLAINTEXT_HOST://localhost:9091
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    volumes:
      - ${KAFKA_DATA_PATH}/kafka-1/data:/var/lib/kafka/data
      - ${KAFKA_DATA_PATH}/kafka-1/config:/etc/kafka
    env_file:
      - .env

  kafka-2:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-2
    expose:
      - 19092
    depends_on:
      - zookeeper-1
      - zookeeper-2
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-1:2181,zookeeper-2:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:19092,PLAINTEXT_HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    volumes:
      - ${KAFKA_DATA_PATH}/kafka-2/data:/var/lib/kafka/data
      - ${KAFKA_DATA_PATH}/kafka-2/config:/etc/kafka
    env_file:
      - .env

  kafka-3:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-3
    expose:
      - 19093
    depends_on:
      - zookeeper-1
      - zookeeper-2
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-1:2181,zookeeper-2:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:19093,PLAINTEXT_HOST://localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    volumes:
      - ${KAFKA_DATA_PATH}/kafka-3/data:/var/lib/kafka/data
      - ${KAFKA_DATA_PATH}/kafka-3/config:/etc/kafka
    env_file:
      - .env

  auth_service:
    build: ./auth_service/
    container_name: auth_service
    command: bash run_app.sh
    expose:
      - 8000
    depends_on:
      - celery
      - postgresdb
      - redis
      - kafka-1
    env_file:
      - ./auth_service/.env

  conversation_service:
    build: ./conversation_service/
    container_name: conversation_service
    command: npm run start:dev
    expose:
      - 3000
    depends_on:
      - mongodb
      - auth_service
      - kafka-2
    env_file:
      - ./conversation_service/.env

  gateway_service:
    build: ./gateway_service/
    container_name: gateway_service
    command: python main.py
    ports:
      - 80:80
    depends_on:
      - auth_service
      - conversation_service
      - kafka-3
    env_file:
      - ./gateway_service/.env
