version: "3.2"

services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - $REDIS_PORT:6379
    volumes: 
      - $REDIS_DATA_PATH:/data
      - $REDIS_DATA_PATH:/mounted-etc/redis.conf
    command: redis-server --requirepass $REDIS_PASSWORD
    env_file:
      - .env